Repository puppetlabs/puppetlabs-tagmail, pull requests merged in 2019-04, with the labels that each got.

#117 checking for logs with level: err
  lib/puppet/reports/tagmail.rb
Labels: bugfix

#123 pdksync - (MODULES-8444) - Raise lower Puppet bound
  metadata.json
Labels: backwards-incompatible

#124 pdksync - (maint) Update pdk-template to f778803
  .gitignore
  .pdkignore
  .puppet-lint.rc
  .travis.yml
  metadata.json
Labels: maintenance
